FOSWIKI_ROOT?=~/foswiki/core
TARGET=\
  jquery.select2.js \
  jquery.select2.init.js \
  jquery.select2.css

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm $(TARGET) *.gz
